### PR TITLE
Check for this.legacyFilesToAppend before getting length

### LINKED ISSUE #24: Doesn't seem to work with ember-cli 3.0.0-beta.2
After updating to ember-cli 3.0 beta, I get the following:

```
- stack: TypeError: Cannot read property 'length' of undefined
    at EmberApp.javascript (/Users/rwwagner/shipshape/shipshape.io/node_modules/ember-cli-tree-shaker/index.js:187:32)
```

### PR DESCRIPTION
**Pull request by rwwagner90**
This should hopefully fix #24.

### CODE REVIEW

**Comment by rwwagner90** [comment]
@kellyselden FWIW I am using my patch branch in my app and it seems to work.

**Comment by ivanvanderbyl** [comment]
It looks like the build is only failing because of chrome not running as root on CI

**Comment by rwwagner90** [comment]
Yeah, I am using my branch in my app and this works fine. Any chance we could merge @kellyselden?

**Comment by kellyselden** [comment]
Fixed in #34. This project is probably going to stop working again with the massive packing refactors we are doing. Thanks for the PR.

**Pull request closed without merging**
